name: Deploy MERN Stack Project
on:
  push:
    branches:
      - master  # Trigger the workflow on push to the 'master' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Deploy to Server (Push Code via SSH)
    - name: Deploy to Server
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.SERVER_HOST }}        # Add your server IP address as a GitHub secret
        username: ${{ secrets.SERVER_USER }}    # Add your server username as a GitHub secret
        key: ${{ secrets.SERVER_SSH_KEY }}      # Add your SSH private key as a GitHub secret
        port: 22                                # Default SSH port (change if necessary)
        script: |
          # Ensure the project directory exists
          if [ ! -d "/var/www/resume-builder" ]; then
            mkdir -p /var/www/resume-builder
          fi
          cd /var/www/resume-builder

          # Pull the latest code from GitHub
          if [ -d ".git" ]; then
            git reset --hard
            git pull origin master
          else
            git clone <repository-url> .
          fi

          # Set up the backend
          cd backend
          npm install
          pm2 start server.js --name resume-builder-backend || pm2 restart resume-builder-backend

          # Set up the frontend
          cd ../frontend
          npm install
          npm run build

          # Move the built frontend files to the Apache root directory
          sudo rm -rf /var/www/html/*
          sudo cp -r build/* /var/www/html/

          # Restart Apache to serve the updated frontend
          sudo systemctl restart apache2
